#!/bin/bash
# sudo yum install mailx
# /opt/zabbix-server/share/zabbix/alertscripts
# sendMail xxx@mail.com subject content
FILE=/tmp/mailtmp.txt
echo "$3">$FILE

dos2unix -k $FILE

/bin/mail -s "$2" $1 < $FILE